### ISSUE TITLE
doxy2swig.py relies on python2, but configure gives it python3

### ISSUE THREAD

**Issue by xorgy** [cmusphinx/sphinxbase#1]
Configure spits out a makefile (doc/Makefile) on systems with python3 which executes doxy2swig.py with PYTHON = /usr/bin/python and PYTHON_VERSION = 3.4(or whatever the local latest version is.

Since doxy2swig.py needs to execute in python2, I needed to modify PYTHON to be /usr/bin/python2.

Is there some way we could have it configure correctly out of the box?

**Comment by nshmyrev** [comment]
Fixed in trunk

**Comment by xorgy** [comment]
Cool. :)
