### ISSUE TITLE
New bin format file size

### ISSUE THREAD

**Issue by Halle** [cmusphinx/sphinxbase#11]
Greetings,

Congratulations on the new trie lm format and special thanks to Vyacheslav Klimkov for implementing it! 

I am experimenting with it right now for OpenEars since producing the DMP format is no longer supported, and I wanted to check in about something I noticed. For a small model where both the DMP and text ARPA model were smaller than 2k, I see a generated .bin file of about 800k. For somewhat larger ones where the DMP used to be around 200k I am now seeing approximately 1MB in filesize for the .bin. Is this increase expected or could this be due to something local to my system?

It is possible to switch to using plain text models for the very small models where I used to use DMP, but for the more medium-sized ones it used to be an advantage that the DMP was a smaller file which could be read in and written out faster than the plain text ARPA model (and it's easier on the media in the case of mobile).

Is it possible to prune or otherwise reduce the .bin format so it's in the same ballpark as the size of the plain-text ARPA files? Thanks for your feedback.

**Comment by nshmyrev** [comment]
Yeah, looks we use too much space for the quantization tables. Kenlm also suffers from that.

I need to think a little bit how to resolve this issue.
