### ISSUE TITLE
n_counts[] being overwritten with uninitialized values for trie models with order 1

### ISSUE THREAD

**Issue by Halle** [cmusphinx/sphinxbase#12]
Hi all,

In the function:

    ngram_model_t* ngram_model_trie_read_arpa(cmd_ln_t *config, const char *path, logmath_t *lmath)

of ngram_model_trie.c, in this block:

    if (order > 1) {
        raw_ngrams = ngrams_raw_read_arpa(&li, base->lmath, counts, order, base->wid);
        ngrams_raw_fix_counts(raw_ngrams, counts, fixed_counts, order);
    }
    for (i = 0; i < order; i++) {
        base->n_counts[i] = fixed_counts[i];
    }
    
base->n_counts[i] is assigned an uninitialized value if the model has an order of 1, causing write_word_str() to later fail since it relies on the real n_counts[0] value. I discovered this using a model with only unigrams. I haven't gotten deeply enough into the new model code to know whether it is as simple as enclosing the for loop in the if statement that precedes it, but since this is new material I thought I'd mention it without yet proposing a fix since perhaps a unigrams-only case hasn't been tested against.

**Comment by nshmyrev** [comment]
Fixed, thanks a lot!

**Comment by Halle** [comment]
Verified working, thanks very much!
