### ISSUE TITLE
Cannot transcribe test audio file

### ISSUE THREAD

**Issue by danj565** [cmusphinx/sphinxbase#15]
Can you please help me out with an issue.. I am attempting to transcribe the test audio file on Centos 6 with the following command: 

sphinx_cont_seg -infile /sphinx/sphinxbase/test/regression/chan3.wav

, but I am getting the following output:

Utterance 0001: file /sphinx/sphinxbase/test/regression/chan3.wav0001.raw start 0.0 sec length 0 samples ( 0.00 sec )

Thank you!

-Dan

**Comment by nshmyrev** [comment]
This command does not transcribe files, it segm.ents them on parts using voice activity detection

**Comment by crisagc** [comment]
Then how could I transcribe text audio file?

**Comment by nshmyrev** [comment]
pocketsphinx_continuous -infile file.wav

overall you can check our tutorial here

http://cmusphinx.sourceforge.net/wiki/tutorial

to understand main components of cmusphinx toolkit
