### ISSUE TITLE
SphinxBase does not recognize Python 3

### ISSUE THREAD

**Issue by THLCX** [cmusphinx/sphinxbase#17]
Hello

I am on a Raspberry 2 system.
The default Python version is 2.7, and Python 3.4 is installed too.
When I try to install Sphinxbase, it simply doesn't recognize my Python3.4 installation, but focus only on the 2.7 version (which has no dependencies installed).
So, how can I install SphinxBase on Python 3.4 ?

Here are the command lines I use :
sudo apt-get update
sudo apt-get upgrade --yes
sudo apt-get install bison
sudo apt-get install libasound2-dev
sudo apt-get install autoconf
sudo apt-get install libtool
git clone https://github.com/cmusphinx/sphinxbase
cd sphinxbase
./autogen.sh --enable-fixed --prefix=/usr
#even this doesn't work : ./autogen.sh --enable-fixed --prefix=/usr/local/lib/python3.4/dist-packages

And the result : 

checking for a Python interpreter with version >= 2.6... python
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking for python2.7... (cached) /usr/bin/python
checking for a version of Python >= '2.1.0'... yes
checking for the distutils Python package... yes
checking for Python include path... -I/usr/include/python2.7
checking for Python library path... -L/usr/lib -lpython2.7
checking for Python site-packages path... /usr/lib/python2.7/dist-packages
checking python extra libraries... -lpthread -ldl  -lutil -lm
checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
checking consistency of all components of python development environment... no
configure: error: in `/home/pi/sphinxbase':
configure: error: 
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LDFLAGS environment variable.
  Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================
See `config.log' for more details

Note that Python-3.4 dev is installed, but the problem is that it does not focus on Python 3.4, only the default 2.7 version...

pi@raspberry ~/sphinxbase $ sudo apt-get install python3.4-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3.4-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberry ~/sphinxbase $ 

Thanks for any help you could provide

**Comment by nshmyrev** [comment]
You can configure in the following way:

       PYTHON=python3.4    ./configure

alternatively you can just remove python2 from your system and make python3 the default.
