### ISSUE TITLE
There is problem with file allocation tables

### ISSUE THREAD

**Issue by oaulakh** [cmusphinx/sphinxbase#18]
There is problem with file allocation tables, means when i try to compile it it shows me that file not exist:

$ python setup.py install
running install
running bdist_egg
running egg_info
writing pocketsphinx.egg-info\PKG-INFO
writing top-level names to pocketsphinx.egg-info\top_level.txt
writing dependency_links to pocketsphinx.egg-info\dependency_links.txt
reading manifest file 'pocketsphinx.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'build'
no previously-included directories found matching 'dist'
writing manifest file 'pocketsphinx.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build
creating build\lib.win32-2.7
creating build\lib.win32-2.7\sphinxbase
copying sphinxbase\swig\python\__init__.py -> build\lib.win32-2.7\sphinxbase
creating build\lib.win32-2.7\pocketsphinx
copying pocketsphinx\swig\python\__init__.py -> build\lib.win32-2.7\pocketsphinx
running build_ext
building 'sphinxbase._sphinxbase' extension
swigging sphinxbase/swig/sphinxbase.i to sphinxbase/swig/sphinxbase_wrap.c
C:\swigwin\swig.exe -python -modern -Isphinxbase/include -Isphinxbase/include/sphinxbase -Isphinxbase/include/win32 -outdir sphinxbase/swig/python -o sphinxbase/swig/sphinxbase_wrap.c sphinxbase/swig/sphinxbase.i
creating build\temp.win32-2.7
creating build\temp.win32-2.7\Release
creating build\temp.win32-2.7\Release\sphinxbase
creating build\temp.win32-2.7\Release\sphinxbase\src
creating build\temp.win32-2.7\Release\sphinxbase\src\libsphinxbase
creating build\temp.win32-2.7\Release\sphinxbase\src\libsphinxbase\lm
creating build\temp.win32-2.7\Release\sphinxbase\src\libsphinxbase\feat
creating build\temp.win32-2.7\Release\sphinxbase\src\libsphinxbase\util
creating build\temp.win32-2.7\Release\sphinxbase\src\libsphinxbase\fe
creating build\temp.win32-2.7\Release\sphinxbase\swig
C:\Users\Sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DHAVE_CONFIG_H -D_CRT_SECURE_NO_DEPRECATE -D_USRDLL -DSPHINXDLL -DWIN32 -D_WINDOWS -DYY_NO_UNISTD_H -Isphinxbase/include -Isphinxbase/include/sphinxbase -Isphinxbase/include/win32 -IC:\Python27\include -IC:\Python27\PC /Tcsphinxbase/src/libsphinxbase/lm\fsg_model.c /Fobuild\temp.win32-2.7\Release\sphinxbase/src/libsphinxbase/lm\fsg_model.obj /wd4244 /wd4267 /wd4197 /wd4090 /wd4018
fsg_model.c
C:\Users\Sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DHAVE_CONFIG_H -D_CRT_SECURE_NO_DEPRECATE -D_USRDLL -DSPHINXDLL -DWIN32 -D_WINDOWS -DYY_NO_UNISTD_H -Isphinxbase/include -Isphinxbase/include/sphinxbase -Isphinxbase/include/win32 -IC:\Python27\include -IC:\Python27\PC /Tcsphinxbase/src/libsphinxbase/lm\jsgf.c /Fobuild\temp.win32-2.7\Release\sphinxbase/src/libsphinxbase/lm\jsgf.obj /wd4244 /wd4267 /wd4197 /wd4090 /wd4018
jsgf.c
C:\Users\Sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DHAVE_CONFIG_H -D_CRT_SECURE_NO_DEPRECATE -D_USRDLL -DSPHINXDLL -DWIN32 -D_WINDOWS -DYY_NO_UNISTD_H -Isphinxbase/include -Isphinxbase/include/sphinxbase -Isphinxbase/include/win32 -IC:\Python27\include -IC:\Python27\PC /Tcsphinxbase/src/libsphinxbase/lm\jsgf_parser.c /Fobuild\temp.win32-2.7\Release\sphinxbase/src/libsphinxbase/lm\jsgf_parser.obj /wd4244 /wd4267 /wd4197 /wd4090 /wd4018
jsgf_parser.c
C:\Users\Sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DHAVE_CONFIG_H -D_CRT_SECURE_NO_DEPRECATE -D_USRDLL -DSPHINXDLL -DWIN32 -D_WINDOWS -DYY_NO_UNISTD_H -Isphinxbase/include -Isphinxbase/include/sphinxbase -Isphinxbase/include/win32 -IC:\Python27\include -IC:\Python27\PC /Tcsphinxbase/src/libsphinxbase/lm\jsgf_scanner.c /Fobuild\temp.win32-2.7\Release\sphinxbase/src/libsphinxbase/lm\jsgf_scanner.obj /wd4244 /wd4267 /wd4197 /wd4090 /wd4018
jsgf_scanner.c
C:\Users\Sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DHAVE_CONFIG_H -D_CRT_SECURE_NO_DEPRECATE -D_USRDLL -DSPHINXDLL -DWIN32 -D_WINDOWS -DYY_NO_UNISTD_H -Isphinxbase/include -Isphinxbase/include/sphinxbase -Isphinxbase/include/win32 -IC:\Python27\include -IC:\Python27\PC /Tcsphinxbase/src/libsphinxbase/lm\lm_trie.c /Fobuild\temp.win32-2.7\Release\sphinxbase/src/libsphinxbase/lm\lm_trie.obj /wd4244 /wd4267 /wd4197 /wd4090 /wd4018
lm_trie.c
sphinxbase/include\sphinxbase/bitarr.h(43) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
error: command 'C:\\Users\\Sony\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

can you please solve this :(

**Comment by mbait** [comment]
Please let us know if
http://stackoverflow.com/questions/126279/c99-stdint-h-header-and-ms-visual-studio
solves the issue.

On Thu, Dec 3, 2015 at 12:30 AM, oaulakh <notifications@github.com> wrote:

> There is problem with file allocation tables, means when i try to compile
> it it shows me that file not exist:
>
> $ python setup.py install
> running install
> running bdist_egg
> running egg_info
> writing pocketsphinx.egg-info\PKG-INFO
> writing top-level names to pocketsphinx.egg-info\top_level.txt
> writing dependency_links to pocketsphinx.egg-info\dependency_links.txt
> reading manifest file 'pocketsphinx.egg-info\SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> no previously-included directories found matching 'build'
> no previously-included directories found matching 'dist'
> writing manifest file 'pocketsphinx.egg-info\SOURCES.txt'
> installing library code to build\bdist.win32\egg
> running install_lib
> running build_py
> creating build
> creating build\lib.win32-2.7
> creating build\lib.win32-2.7\sphinxbase
> copying sphinxbase\swig\python__init__.py -> build\lib.win32-2.7\sphinxbase
> creating build\lib.win32-2.7\pocketsphinx
> copying pocketsphinx\swig\python__init__.py ->
> build\lib.win32-2.7\pocketsphinx
> running build_ext
> building 'sphinxbase._sphinxbase' extension
> swigging sphinxbase/swig/sphinxbase.i to sphinxbase/swig/sphinxbase_wrap.c
> C:\swigwin\swig.exe -python -modern -Isphinxbase/include
> -Isphinxbase/include/sphinxbase -Isphinxbase/include/win32 -outdir
> sphinxbase/swig/python -o sphinxbase/swig/sphinxbase_wrap.c
> sphinxbase/swig/sphinxbase.i
> creating build\temp.win32-2.7
> creating build\temp.win32-2.7\Release
> creating build\temp.win32-2.7\Release\sphinxbase
> creating build\temp.win32-2.7\Release\sphinxbase\src
> creating build\temp.win32-2.7\Release\sphinxbase\src\libsphinxbase
> creating build\temp.win32-2.7\Release\sphinxbase\src\libsphinxbase\lm
> creating build\temp.win32-2.7\Release\sphinxbase\src\libsphinxbase\feat
> creating build\temp.win32-2.7\Release\sphinxbase\src\libsphinxbase\util
> creating build\temp.win32-2.7\Release\sphinxbase\src\libsphinxbase\fe
> creating build\temp.win32-2.7\Release\sphinxbase\swig
> C:\Users\Sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for
> Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG
> -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DHAVE_CONFIG_H
> -D_CRT_SECURE_NO_DEPRECATE -D_USRDLL -DSPHINXDLL -DWIN32 -D_WINDOWS
> -DYY_NO_UNISTD_H -Isphinxbase/include -Isphinxbase/include/sphinxbase
> -Isphinxbase/include/win32 -IC:\Python27\include -IC:\Python27\PC
> /Tcsphinxbase/src/libsphinxbase/lm\fsg_model.c
> /Fobuild\temp.win32-2.7\Release\sphinxbase/src/libsphinxbase/lm\fsg_model.obj
> /wd4244 /wd4267 /wd4197 /wd4090 /wd4018
> fsg_model.c
> C:\Users\Sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for
> Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG
> -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DHAVE_CONFIG_H
> -D_CRT_SECURE_NO_DEPRECATE -D_USRDLL -DSPHINXDLL -DWIN32 -D_WINDOWS
> -DYY_NO_UNISTD_H -Isphinxbase/include -Isphinxbase/include/sphinxbase
> -Isphinxbase/include/win32 -IC:\Python27\include -IC:\Python27\PC
> /Tcsphinxbase/src/libsphinxbase/lm\jsgf.c
> /Fobuild\temp.win32-2.7\Release\sphinxbase/src/libsphinxbase/lm\jsgf.obj
> /wd4244 /wd4267 /wd4197 /wd4090 /wd4018
> jsgf.c
> C:\Users\Sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for
> Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG
> -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DHAVE_CONFIG_H
> -D_CRT_SECURE_NO_DEPRECATE -D_USRDLL -DSPHINXDLL -DWIN32 -D_WINDOWS
> -DYY_NO_UNISTD_H -Isphinxbase/include -Isphinxbase/include/sphinxbase
> -Isphinxbase/include/win32 -IC:\Python27\include -IC:\Python27\PC
> /Tcsphinxbase/src/libsphinxbase/lm\jsgf_parser.c
> /Fobuild\temp.win32-2.7\Release\sphinxbase/src/libsphinxbase/lm\jsgf_parser.obj
> /wd4244 /wd4267 /wd4197 /wd4090 /wd4018
> jsgf_parser.c
> C:\Users\Sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for
> Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG
> -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DHAVE_CONFIG_H
> -D_CRT_SECURE_NO_DEPRECATE -D_USRDLL -DSPHINXDLL -DWIN32 -D_WINDOWS
> -DYY_NO_UNISTD_H -Isphinxbase/include -Isphinxbase/include/sphinxbase
> -Isphinxbase/include/win32 -IC:\Python27\include -IC:\Python27\PC
> /Tcsphinxbase/src/libsphinxbase/lm\jsgf_scanner.c
> /Fobuild\temp.win32-2.7\Release\sphinxbase/src/libsphinxbase/lm\jsgf_scanner.obj
> /wd4244 /wd4267 /wd4197 /wd4090 /wd4018
> jsgf_scanner.c
> C:\Users\Sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for
> Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG
> -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DHAVE_CONFIG_H
> -D_CRT_SECURE_NO_DEPRECATE -D_USRDLL -DSPHINXDLL -DWIN32 -D_WINDOWS
> -DYY_NO_UNISTD_H -Isphinxbase/include -Isphinxbase/include/sphinxbase
> -Isphinxbase/include/win32 -IC:\Python27\include -IC:\Python27\PC
> /Tcsphinxbase/src/libsphinxbase/lm\lm_trie.c
> /Fobuild\temp.win32-2.7\Release\sphinxbase/src/libsphinxbase/lm\lm_trie.obj
> /wd4244 /wd4267 /wd4197 /wd4090 /wd4018
> lm_trie.c
> sphinxbase/include\sphinxbase/bitarr.h(43) : fatal error C1083: Cannot
> open include file: 'stdint.h': No such file or directory
> error: command
> 'C:\Users\Sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for
> Python\9.0\VC\Bin\cl.exe' failed with exit status 2
>
> can you please solve this :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmusphinx/sphinxbase/issues/18>.
>



-- 
Sincerely, Alexander

**Comment by nshmyrev** [comment]
Fixed now, I removed unnecessary stdint include.

**Comment by oaulakh** [comment]
yup it installed now, it's working thanks
