### ISSUE TITLE
Please create a label or a branch so it is easy to lock down to a specific version

### ISSUE THREAD

**Issue by jainanshul** [cmusphinx/sphinxbase#22]
I would like to lock down the version of sphinxbase to a specific branch or a tag so I don't keep on importing new commits as they come. It would be great if you guys can create a tag or a branch that could be used.

**Comment by nshmyrev** [comment]
You can just retrieve specific commit

**Comment by jainanshul** [comment]
Yes I can do that and I am, but a tag or a branch is preferable over a random commit #.
