### ISSUE TITLE
Can't make install

### ISSUE THREAD

**Issue by zkirill** [cmusphinx/sphinxbase#25]
Downloaded sphinxbase-5prealpha.tar.gz from Sourceforge, ran ./configure and make and get this error on FreeBSD 10 and 11:

```
...
Making all in swig
Making all in python
/usr/local/bin/swig2.0 -I../../include  -outdir . -o sphinxbase_wrap.c -python
Must specify an input file. Use -help for available options.
*** Error code 1

Stop.
make[2]: stopped in /root/sphinxbase-5prealpha/swig/python
*** Error code 1

Stop.
make[1]: stopped in /root/sphinxbase-5prealpha/swig
*** Error code 1

Stop.
make: stopped in /root/sphinxbase-5prealpha
```

**Comment by nshmyrev** [comment]
This is freebsd make/automake issue:

https://lists.gnu.org/archive/html/discuss-gnuradio/2005-07/msg00077.html

I think you need to use gmake.

We also recommend to use swig3.

**Comment by zkirill** [comment]
@nshmyrev Thank you very much! Using gmake and swig3 worked.
