### ISSUE TITLE
configure error: swig not found

### ISSUE THREAD

**Issue by che-effe** [cmusphinx/sphinxbase#28]
The swig directory is definitely present, but when running `./configure` I'm getting the following error ```configure: error: swig not found```
running in mac terminal unix bash
Any help would be really apprecaited.

**Comment by nshmyrev** [comment]
Swig is a command line tool, not a directory. You need to install swig with your package manager for example.

**Comment by che-effe** [comment]
Thank you that's definitely the piece I was missing.
