### ISSUE TITLE
CMake build system

### ISSUE THREAD

**Issue by syb0rg** [cmusphinx/sphinxbase#29]
This repository lacks a CMake build system, which is the modern day Autotools.  Are there plans to implement this in the future?

**Comment by nshmyrev** [comment]
No, I don't think it is needed. Thank you for the suggestion.

**Comment by syb0rg** [comment]
Right now I'm depending on this software in one of my projects: [Khronos](https://github.com/syb0rg/Khronos).  [Because it has so many sub-dependencies](https://github.com/syb0rg/Khronos/issues/7), I'm having issues building this dependency portably.  The fix is quite simple, migrate to a CMake build system.

I'm quite surprised that this software doesn't have CMake already integrated.  Looking at the [Wikipedia page](https://en.wikipedia.org/wiki/CMake), you'll see that lots of modern day software using CMake as their primary build system; that list is also missing a few bigger projects I know of.

You may not think it is needed, but you also aren't the only user of this software.  As a software developer, you are supposed to develop for your users.  I ask that you reconsider implementing this (it shouldn't take that long to implement properly).
