### ISSUE TITLE
If you are running into weird errors to do with Makefiles

### ISSUE THREAD

**Issue by siemanko** [cmusphinx/sphinxbase#3]
Make sure that you have libtool installed and run libtoolize before running autogen.sh.

I don't know much about makefiles/autogen, but that fixed a headache for me, so I decided to share.

Also shouldn't libtoolize run by default in autogen.sh?

**Comment by waqarrashid33** [comment]
./autogen.sh was giving this error. I had to install "Automake 1.10" to make it work. I am not sure though, if this was the main reason. The error is given below

**Error**: You must have `autoconf' installed to.
Download the appropriate package for your distribution,
or get the source tarball at ftp://ftp.gnu.org/pub/gnu/

**Error**: You must have `libtool' installed.
Get ftp://ftp.gnu.org/pub/gnu/libtool/libtool-2.2.6b.tar.gz
(or a newer version if it is available)

**Error**: You must have `automake' installed.
Get ftp://ftp.gnu.org/pub/gnu/automake/automake-1.11.tar.gz
(or a newer version if it is available)
