### ISSUE TITLE
ImportError: No module named _ad

### ISSUE THREAD

**Issue by ankurgulati** [cmusphinx/sphinxbase#35]
Hi,
I am facing a error while importing please help I am using the following command in python 2.7 
`from sphinxbase import *`

And following is the error:
> ImportError: No module named _ad

**Comment by nshmyrev** [comment]
It is an issue for pocketsphinx-python, has no relation to our codebase.

**Comment by nshmyrev** [comment]
Tracked at https://github.com/bambocher/pocketsphinx-python/issues/19
