### ISSUE TITLE
[Fix included] --debug doesn't filter messages

### ISSUE THREAD

**Issue by krwq** [cmusphinx/sphinxbase#36]
It seems that --debug switch has no effect on what gets printed on screen. In demos like pocketsphinx/continuable.c it is pretty annoying to see all these messages.

I also made a fix here: https://github.com/cmusphinx/sphinxbase/pull/37

**Comment by nshmyrev** [comment]
I'm sorry, info messages are critical for debugging accuracy and performance issues, until now we have to report them by default because too many newbies do not even bother to read the forum and accuracy is usually unstable.

**Comment by impala454** [comment]
Perhaps a functionality to set the print level of the E_* functions?  Sure, leave the defaults what makes sense but at least give the ability to eliminate the spam.  INFO messages shouldn't automatically be spammed to `std::cerr` with no way at all to change it.

**Comment by nshmyrev** [comment]
@impala454 you can redefine logging behavior with `err_set_cb`, you can filter INFO there.

**Comment by impala454** [comment]
Ok thanks.  While that does solve the issue it seems counter intuitive to have the user need to re-implement logging functions simply to choose what level of messages to display.  It seems like an awfully simply change to make as the default error callback functions all have the needed error level already passed in as parameters.  And you could make it default to display all INFO to alleviate the issue you brought up above.

**Comment by mbait** [comment]
@impala454 This is free software. If you think something can be improved, your patches are welcome. You also can use utils like `grep` and `awk` to filter out everything except what you need.

**Comment by impala454** [comment]
@mbait I think your statements regarding free software go without saying.  I certainly will contribute (and likely fix this particular issue) if we end up using this library.  Regardless, it seems this issue should remain open.  When using this library as an actual library for another application, `grep` and `awk` does not help.  Most logging systems provide the ability to determine log level at initialization.  Even the file comment on the `err.c` file specifically states `Somewhat antiquated logging and error interface.`.  The simple suggestion here is that it's an actual issue and to leave it open.

**Comment by nshmyrev** [comment]
Thank you for suggestion, @impala454, we'll consider that. For now you can use existing API, it is flexible enough.
