### ISSUE TITLE
Cross compiling to arm : error after doing make

### ISSUE THREAD

**Issue by hmd13** [cmusphinx/sphinxbase#49]
Hi, I'm trying to get the sphinxbase, the pocketsphinx and the sphinxtrain libraries on ARM core.

Starting with sphinxbase, I'm cross-compiling using the toolchain arm-linux-gnueabi with this configuration: ./configure --host=arm-linux-gnueabi --build=x86_64-linux-gnu --without-python --prefix=/home/installation/directory

I got no error with configure but after doing: make CC=arm-linux-gueabi-gcc, the makefile stopped compiling and I got the following error: 

```
Entering directory '/home/ubuntu/Desktop/sphinx-github/sphinxbase/src/sphinx_adtools'
/bin/bash ../../libtool  --tag=CC   --mode=link arm-linux-gnueabi-gcc -I../../include -I../../include -g -O2 -Wall   -o sphinx_cont_seg cont_seg.o ../../src/libsphinxbase/libsphinxbase.la ../../src/libsphinxad/libsphinxad.la -lpthread -lm 
libtool: link: arm-linux-gnueabi-gcc -I../../include -I../../include -g -O2 -Wall -o .libs/sphinx_cont_seg cont_seg.o  ../../src/libsphinxbase/.libs/libsphinxbase.so ../../src/libsphinxad/.libs/libsphinxad.so -lpthread -lm -Wl,-rpath -Wl,/home/sphinx/lib
../../src/libsphinxad/.libs/libsphinxad.so: undefined reference to `pa_strerror'
../../src/libsphinxad/.libs/libsphinxad.so: undefined reference to `pa_simple_read'
../../src/libsphinxad/.libs/libsphinxad.so: undefined reference to `pa_simple_new'
../../src/libsphinxad/.libs/libsphinxad.so: undefined reference to `pa_simple_free'
collect2: error: ld returned 1 exit status
Makefile:413: recipe for target 'sphinx_cont_seg' failed
make[2]: *** [sphinx_cont_seg] Error 1
make[2]: Leaving directory '/home/ubuntu/Desktop/sphinx-github/sphinxbase/src/sphinx_adtools'
Makefile:374: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/Desktop/sphinx-github/sphinxbase/src'
Makefile:479: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```
Is there a way to fix this ? Thank you.

**Comment by nshmyrev** [comment]
Already covered at https://sourceforge.net/p/cmusphinx/discussion/help/thread/f9275d1c/

**Comment by pxmage** [comment]
> Nickolay V. Shmyrev - 2016-11-10
I'll try to fix it in coming days. As a quick fix you can remove checks for pulseaudio and alsa in configure.ac and run autogen.sh.

I ran into the same problem as well, and seems it still not fixed? Or I just need to do as what the "quick fix" tell me to do?

**Comment by pxmage** [comment]
Hey, I have just finished cross-compile successfully and just wanna let other guys who ran into the same problem to know: 

You can just comment `sphinxad` and its related stuff inside Makefiles (if you don't need to use sphinxad), and then you can do cross-compile smoothly. (Also you need to comment `sphinxad` related stuff in pocketsphinx or you will get errors while building pocket sphinx.)
