### ISSUE TITLE
build_for_iphone.sh missing

### ISSUE THREAD

**Issue by mrwaim** [cmusphinx/sphinxbase#5]
Hi,

I dont see the build_for_iphone.sh file.

I've tried to do autogen, configure, and make, in case its only built after building, and its still not there.

I've tried find $PWD -name build_for_iphone.sh -type file in case it is in some folder, still no luck.

Am I missing something obvious?

Thanks,
Ibrahim

**Comment by nshmyrev** [comment]
This script was removed, you can use OpenEars instead.

**Comment by mrwaim** [comment]
Could you update the documentation? Readme still references it.

**Comment by nshmyrev** [comment]
Updated, thank you for report. I've also created pocketsphinx-ios-demo which we probably going to extend to more functional project.
