### ISSUE TITLE
Can't compile project with /zw option

### ISSUE THREAD

**Issue by coal2001** [cmusphinx/sphinxbase#51]
Compile option /zw is needed to create UWP (Universal Windows Project in Visual Studio), which used in Windows 10 IoT on mobile devices. I'd planned to use this OS in my Raspberry Pi 3, but have no way to get PocketSphynx work with it.

I guess it needs to refactor project with no low-level audio (realize functions with byte buffer, wich would be sent from high-level c# audio funcs of Windows IoT)

Final wish is to compile sphinxbase in Visual Studio as UWP (Universal Windows Project). Currently there is no way to do so for some restrictions.

**Comment by nshmyrev** [comment]
What is the problem exactly? You are not very clear. So did you try to compile and what happened?

**Comment by coal2001** [comment]
here is msdn instruction of port c++ to c++ uwp 
https://msdn.microsoft.com/en-us/library/mt186162.aspx

1. I tried only to switch /zw on . And get error:

cannot compile C file "..\..\src\libsphinxad\ad_win32.c" with  /ZW

problem is with LPWAVEHDR and HWAVEIN as I consider. Maybe not only with them.
