### ISSUE TITLE
Error while converting from bin to text

### ISSUE THREAD

**Issue by zeryabmoussaoui** [cmusphinx/sphinxbase#52]
Hello
I'm on Ubuntu and when i tried to execute the following command : 

sudo sphinx_lm_convert -i language-model.lm.bin -ifmt bin -o language-model.lm -ofmt arp 

I'm getting the error "ERROR: "sphinx_lm_convert.c", line 158: Invalid input type bin"
Does-it mean that the argument "bin" is invalid or that my file is not valid ?
I looked in the code,  the argument "bin" is the one expected.
i also tried with no "ifmt" argument ( to guess it is a bin), and it also gives the error : 
"ERROR: "ngram_model_dmp.c", line 121: Wrong magic header size number 54726965: language-model.lm.bin is not a dump file"

Thank for reading.

**Comment by nshmyrev** [comment]
You are using outdated version.

**Comment by zeryabmoussaoui** [comment]
Thanks for your response. 
I was using the one on the apt repository, i will try to compile from source.
It may need an update.

**Comment by zeryabmoussaoui** [comment]
I updated on the last commit, I'm getting now the following error : 
sphinx_lm_convert: ngram_model_trie.c:279: ngram_model_trie_write_arpa: Assertion `raw_ngram_idx == base->n_counts[i - 1]' failed.
