### ISSUE TITLE
Compile warnings for missing headers

### ISSUE THREAD

**Issue by leecbaker** [cmusphinx/sphinxbase#59]
I am getting a couple of compile warnings that are trivially fixable:

`gettimeofday()` in `util/profile.c` needs the header `#include <sys/time.h>` included.

`unlink()` in the same file needs `#include <unistd.h>`

Should be an easy / quick fix.

**Comment by nshmyrev** [comment]
It is already there

https://github.com/cmusphinx/sphinxbase/blob/master/src/libsphinxbase/util/profile.c#L76
