### ISSUE TITLE
sphinx_lm_convert: cannot open shared object file

### ISSUE THREAD

**Issue by matthiaaas** [cmusphinx/sphinxbase#65]
Hey, just installed sphinxbase on Linux, but command `sphinx_lm_convert` raises an error when I try to convert an ARPA language model file to binary
 `~ /DIRECTORY/  $ sphinx_lm_convert -i de-de.arpa -o de-de.lm.binary`.
`
sphinx_lm_convert: error while loading shared libraries: libsphinxbase.so.3: cannot open shared object file: No such file or directory
`
that doesn't appear conclusive to me.
Is that caused because of the file extension .arpa and not .lm.arpa?

**Comment by nshmyrev** [comment]
You need to set LD_LIBRARY_PATH or configure /etc/ld.so.conf
