### ISSUE TITLE
ad_win32.c prints to stdout/stderr instead of using the logging macros from err.h

### ISSUE THREAD

**Issue by 1HPorange** [cmusphinx/sphinxbase#70]
What the title says. You get stuff like

```
Allocating 32 buffers of 2500 samples each
```

in the console despite `-logn nul`.

If you want I can make a pull request.

**Comment by nshmyrev** [comment]
I've just removed the message, so it should be ok.

But the problem is more complex that you might think. The reason is that libsphinxad library does not depend on sphinxbase core (for some reasons) so it does not use sphinxbase logging and does not respect logfn. I'm not sure how to fix it easily.
