### ISSUE TITLE
Build location for Windows \\bin unable to find files

### ISSUE THREAD

**Issue by JackWoolford** [cmusphinx/sphinxbase#8]
So as is stated in the title all the built files on Windows no matter what I seem to change builds executables that think the files are in \\bin\debug or \\bin\release which obviously doesn't end up working and just results in the executable closing.

Anyway a fix for this would be appreciated, thanks!

**Comment by nshmyrev** [comment]
Not sure what your problem is, you need to spend some more time explaining it.

**Comment by JackWoolford** [comment]
Okay sorry, I guess I wasn't clear enough. Maybe if I post the output of the build it will make sense.

1>------ Rebuild All started: Project: sphinxbase, Configuration: Release Win32 ------
1>  ad_win32.c
1>  agc.c
1>  cmn.c
1>  cmn_prior.c
1>  feat.c
1>..\..\src\libsphinxbase\feat\feat.c(820): warning C4018: '<' : signed/unsigned mismatch
1>..\..\src\libsphinxbase\feat\feat.c(900): warning C4018: '<' : signed/unsigned mismatch
1>..\..\src\libsphinxbase\feat\feat.c(903): warning C4018: '<' : signed/unsigned mismatch
1>  lda.c
1>  fe_interface.c
1>  fe_noise.c
1>  fe_prespch_buf.c
1>  fe_sigproc.c
1>  fe_warp_affine.c
1>  fe_warp.c
1>  fe_warp_inverse_linear.c
1>  fe_warp_piecewise_linear.c
1>  fixlog.c
1>  yin.c
1>  fsg_model.c
1>..\..\src\libsphinxbase\lm\fsg_model.c(668): warning C4244: '=' : conversion from 'double' to 'float32', possible loss of data
1>..\..\src\libsphinxbase\lm\fsg_model.c(871): warning C4244: 'function' : conversion from 'float32' to 'int', possible loss of data
1>  jsgf.c
1>..\..\src\libsphinxbase\lm\jsgf.c(925): warning C4090: 'function' : different 'const' qualifiers
1>  jsgf_parser.c
1>  jsgf_scanner.c
1>jsgf_scanner.c(922): warning C4018: '<' : signed/unsigned mismatch
1>_jsgf_scanner.l(84): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
1>jsgf_scanner.c(1819): warning C4018: '<' : signed/unsigned mismatch
1>  Generating Code...
1>  Compiling...
1>  lm3g_model.c
1>  ngram_model_arpa.c
1>c:\users\jack\desktop\sphinxbase\src\libsphinxbase\lm\lm3g_templates.c(56): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\jack\desktop\sphinxbase\src\libsphinxbase\lm\lm3g_templates.c(58): warning C4018: '>' : signed/unsigned mismatch
1>  ngram_model.c
1>..\..\src\libsphinxbase\lm\ngram_model.c(512): warning C4018: '<' : signed/unsigned mismatch
1>  ngram_model_dmp.c
1>..\..\src\libsphinxbase\lm\ngram_model_dmp.c(663): warning C4244: '=' : conversion from 'float64' to 'float32', possible loss of data
1>..\..\src\libsphinxbase\lm\ngram_model_dmp.c(665): warning C4244: '=' : conversion from 'float64' to 'float32', possible loss of data
1>..\..\src\libsphinxbase\lm\ngram_model_dmp.c(817): warning C4244: 'initializing' : conversion from 'float64' to 'float32', possible loss of data
1>..\..\src\libsphinxbase\lm\ngram_model_dmp.c(830): warning C4244: 'initializing' : conversion from 'float64' to 'float32', possible loss of data
1>..\..\src\libsphinxbase\lm\ngram_model_dmp.c(843): warning C4244: 'initializing' : conversion from 'float64' to 'float32', possible loss of data
1>  ngram_model_set.c
1>..\..\src\libsphinxbase\lm\ngram_model_set.c(549): warning C4244: '=' : conversion from 'double' to 'float32', possible loss of data
1>..\..\src\libsphinxbase\lm\ngram_model_set.c(602): warning C4244: '=' : conversion from 'float64' to 'float32', possible loss of data
1>..\..\src\libsphinxbase\lm\ngram_model_set.c(807): warning C4244: 'function' : conversion from 'float64' to 'float32', possible loss of data
1>  bio.c
1>  bitvec.c
1>  blas_lite.c
1>  case.c
1>  ckd_alloc.c
1>  cmd_ln.c
1>..\..\src\libsphinxbase\util\cmd_ln.c(151): warning C4090: 'function' : different 'const' qualifiers
1>..\..\src\libsphinxbase\util\cmd_ln.c(332): warning C4090: 'function' : different 'const' qualifiers
1>  dtoa.c
1>  err.c
1>  f2c_lite.c
1>  filename.c
1>  genrand.c
1>  glist.c
1>  hash_table.c
1>  heap.c
1>  huff_code.c
1>..\..\src\libsphinxbase\util\huff_code.c(339): warning C4018: '<' : signed/unsigned mismatch
1>..\..\src\libsphinxbase\util\huff_code.c(393): warning C4018: '<' : signed/unsigned mismatch
1>..\..\src\libsphinxbase\util\huff_code.c(429): warning C4018: '<' : signed/unsigned mismatch
1>..\..\src\libsphinxbase\util\huff_code.c(460): warning C4018: '<' : signed/unsigned mismatch
1>  Generating Code...
1>  Compiling...
1>  listelem_alloc.c
1>  logmath.c
1>  matrix.c
1>..\..\src\libsphinxbase\util\matrix.c(71): warning C4244: '*=' : conversion from 'float64' to 'float32', possible loss of data
1>  mmio.c
1>  pio.c
1>  profile.c
1>  sbthread.c
1>  slamch.c
1>  slapack_lite.c
1>..\..\src\libsphinxbase\util\slapack_lite.c(1041): warning C4244: '=' : conversion from 'doublereal' to 'real', possible loss of data
1>..\..\src\libsphinxbase\util\slapack_lite.c(1046): warning C4244: '=' : conversion from 'double' to 'real', possible loss of data
1>..\..\src\libsphinxbase\util\slapack_lite.c(1074): warning C4244: '=' : conversion from 'doublereal' to 'real', possible loss of data
1>..\..\src\libsphinxbase\util\slapack_lite.c(1079): warning C4244: '=' : conversion from 'double' to 'real', possible loss of data
1>  strfuncs.c
1>  Generating Code...
1>     Creating library ../../bin/Release/Win32/sphinxbase.lib and object ../../bin/Release/Win32/sphinxbase.exp
1>  sphinxbase.vcxproj -> C:\Users\Jack\Desktop\sphinxbase\\bin\Release\Win32\sphinxbase.dll
2>------ Rebuild All started: Project: sphinx_cepview, Configuration: Release Win32 ------
3>------ Rebuild All started: Project: sphinx_fe, Configuration: Release Win32 ------
4>------ Rebuild All started: Project: sphinx_jsgf2fsg, Configuration: Release Win32 ------
5>------ Rebuild All started: Project: sphinx_lm_convert, Configuration: Release Win32 ------
4>  main.c
5>  sphinx_lm_convert.c
2>  main_cepview.c
3>  sphinx_fe.c
3>..\..\src\sphinx_fe\sphinx_fe.c(371): warning C4018: '<' : signed/unsigned mismatch
2>  sphinx_cepview.vcxproj -> C:\Users\Jack\Desktop\sphinxbase\\bin\Release\Win32\sphinx_cepview.exe
4>  sphinx_jsgf2fsg.vcxproj -> C:\Users\Jack\Desktop\sphinxbase\\bin\Release\Win32\sphinx_jsgf2fsg.exe
5>  sphinx_lm_convert.vcxproj -> C:\Users\Jack\Desktop\sphinxbase\\bin\Release\Win32\sphinx_lm_convert.exe
3>  sphinx_fe.vcxproj -> C:\Users\Jack\Desktop\sphinxbase\\bin\Release\Win32\sphinx_fe.exe
6>------ Rebuild All started: Project: sphinx_pitch, Configuration: Release Win32 ------
7>------ Rebuild All started: Project: sphinx_seg, Configuration: Release Win32 ------
6>  sphinx_pitch.c
7>  cont_seg.c
6>  sphinx_pitch.vcxproj -> C:\Users\Jack\Desktop\sphinxbase\\bin\Release\Win32\sphinx_pitch.exe
7>  sphinx_seg.vcxproj -> C:\Users\Jack\Desktop\sphinxbase\\bin\Release\Win32\sphinx_seg.exe
========== Rebuild All: 7 succeeded, 0 failed, 0 skipped ==========

See just above here, the vcxproj output is to \\bin\Release which when you try and run the executables that were built it errors out because it can't find the other files because it thinks they are in \\bin which doesn't exist. The \\ is the issue. Hopefully that helps. The same error is also occuring in pocketsphinx by the way.

**Comment by nshmyrev** [comment]
> ========== Rebuild All: 7 succeeded, 0 failed, 0 skipped ==========

Build is successful, I do not see a problem here.

> See just above here, the vcxproj output is to \bin\Release which when you try and run the executables that were built it errors out because it can't find the other files because it thinks they are in \bin which doesn't exist. The \ is the issue. Hopefully that helps. The same error is also occuring in pocketsphinx by the way.

What executables do you try to run? What parameters? What is the error you see exactly? Sorry, I am not from NSA to access your mind and check that.

**Comment by JackWoolford** [comment]
I'm really sorry, seems I managed to not understand what I was doing and thus thought it wasn't working, everything is fixed and working again now, thanks.

Also would you mind pointing me in the right direction on training Pocketsphinx so that it can understand like a dictionary of words and also be more accurate transcribing any English speaking voice?

**Comment by nshmyrev** [comment]
Ok, great

Most of the things are covered in our tutorial http://cmusphinx.sourceforge.net/wiki/tutorial
