### ISSUE TITLE
make[2]: Nothing to be done for `all-am'. 

### ISSUE THREAD

**Issue by sharyuke** [cmusphinx/sphinxbase#9]
when i making the project  i got follow issues..

make[2]: Nothing to be done for `all-am'.
Making all in doc
make[1]: Nothing to be done for `all'.
Making all in include
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in sphinxbase
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all-am'.
Making all in test
Making all in unit
Making all in test_alloc
make[3]: Nothing to be done for `all'.
Making all in test_bitvec
make[3]: Nothing to be done for `all'.
Making all in test_case
make[3]: Nothing to be done for `all'.

and so on

**Comment by nshmyrev** [comment]
This is an expected build log. There is no issue here.
